import prisma from "@/prisma/prisma";
import {
  Task,
  TaskType,
  RecurrenceFrequency,
  RecurrenceDuration,
} from "@prisma/client";
import { addDays, addWeeks, addMonths, addYears, isBefore } from "date-fns";

// Safe user select to exclude sensitive fields
const safeUserSelect = {
  id: true,
  name: true,
  email: true,
  image: true,
  emailVerified: true,
} as const;

export const createEvent = async (
  data: Omit<
    Task,
    "createdAt" | "updatedAt" | "id" | "parentId" | "originalEventId"
  >
) => {
  try {
    console.log("create event db", data);
    return await prisma.task.create({
      data: {
        ...data,
        taskType: TaskType.EVENT,
      },
    });
  } catch (e) {
    console.log(JSON.stringify(e));
    throw new Error("Failed to create event");
  }
};

export const getEventsByWorkspaceId = async (workspaceId: string) => {
  return await prisma.task.findMany({
    where: {
      workspaceId,
      taskType: TaskType.EVENT,
    },
    include: {
      project: true,
      assignee: { include: { user: { select: safeUserSelect } } },
      createdBy: { include: { user: { select: safeUserSelect } } },
      worklogs: {
        include: {
          member: {
            include: {
              user: { select: safeUserSelect },
            },
          },
        },
        orderBy: {
          dateWorked: "desc",
        },
      },
      assets: true,
      category: true,
      originalEvent: true,
      eventOccurrences: true,
    },
  });
};

export const getEventsByProjectId = async (projectId: string) => {
  return await prisma.task.findMany({
    where: {
      projectId,
      taskType: TaskType.EVENT,
    },
    include: {
      project: true,
      assignee: { include: { user: { select: safeUserSelect } } },
      createdBy: { include: { user: { select: safeUserSelect } } },
      worklogs: {
        include: {
          member: {
            include: {
              user: { select: safeUserSelect },
            },
          },
        },
        orderBy: {
          dateWorked: "desc",
        },
      },
      assets: true,
      category: true,
      originalEvent: true,
      eventOccurrences: true,
    },
  });
};

export const getEventsInDateRange = async (
  workspaceId: string,
  startDate: Date,
  endDate: Date
) => {
  return await prisma.task.findMany({
    where: {
      workspaceId,
      taskType: TaskType.EVENT,
      dueDate: {
        gte: startDate,
        lte: endDate,
      },
    },
    include: {
      project: true,
      assignee: { include: { user: { select: safeUserSelect } } },
      createdBy: { include: { user: { select: safeUserSelect } } },
      category: true,
      originalEvent: true,
    },
  });
};

export const generateEventOccurrences = async (eventId: string) => {
  const event = await prisma.task.findUnique({
    where: { id: eventId },
  });

  if (
    !event ||
    !event.isRecurring ||
    !event.dueDate ||
    !event.recurrenceFrequency
  ) {
    return [];
  }

  const occurrences = [];
  let currentDate = new Date(event.dueDate);
  const endDate = getRecurrenceEndDate(event);

  // Generate occurrences up to the end date
  while (isBefore(currentDate, endDate)) {
    // Skip the original event date
    if (currentDate.getTime() !== event.dueDate.getTime()) {
      occurrences.push({
        ...event,
        id: undefined, // Will be generated by Prisma
        dueDate: new Date(currentDate),
        originalEventId: eventId,
        isRecurring: false, // Occurrences are not recurring themselves
        recurrenceFrequency: null,
        recurrenceDuration: null,
        recurrenceEndDate: null,
        createdAt: undefined,
        updatedAt: undefined,
      });
    }

    currentDate = getNextOccurrenceDate(currentDate, event.recurrenceFrequency);
  }

  // Create all occurrences in the database
  if (occurrences.length > 0) {
    await prisma.task.createMany({
      data: occurrences,
    });
  }

  return occurrences;
};

export const deleteEventOccurrences = async (originalEventId: string) => {
  return await prisma.task.deleteMany({
    where: {
      originalEventId,
    },
  });
};

export const deleteEventAndOccurrences = async (eventId: string) => {
  // First delete all occurrences
  await prisma.task.deleteMany({
    where: {
      originalEventId: eventId,
    },
  });

  // Then delete the original event
  return await prisma.task.delete({
    where: {
      id: eventId,
    },
  });
};

export const updateEventAndOccurrences = async (
  eventId: string,
  data: Partial<Task>
) => {
  // Update the original event
  const updatedEvent = await prisma.task.update({
    where: { id: eventId },
    data,
  });

  // If the event is recurring, regenerate occurrences
  if (updatedEvent.isRecurring && updatedEvent.recurrenceFrequency) {
    // Delete existing occurrences
    await deleteEventOccurrences(eventId);

    // Generate new occurrences
    await generateEventOccurrences(eventId);
  }

  return updatedEvent;
};

// Helper function to get the next occurrence date
function getNextOccurrenceDate(
  currentDate: Date,
  frequency: RecurrenceFrequency
): Date {
  switch (frequency) {
    case RecurrenceFrequency.DAILY:
      return addDays(currentDate, 1);
    case RecurrenceFrequency.WEEKLY:
      return addWeeks(currentDate, 1);
    case RecurrenceFrequency.MONTHLY:
      return addMonths(currentDate, 1);
    case RecurrenceFrequency.ANNUALLY:
      return addYears(currentDate, 1);
    default:
      return addDays(currentDate, 1);
  }
}

// Helper function to get the recurrence end date
function getRecurrenceEndDate(event: Task): Date {
  const startDate = event.dueDate!;

  switch (event.recurrenceDuration) {
    case RecurrenceDuration.ONE_MONTH:
      return addMonths(startDate, 1);
    case RecurrenceDuration.ONE_YEAR:
      return addYears(startDate, 1);
    case RecurrenceDuration.CUSTOM:
      return event.recurrenceEndDate || addYears(startDate, 1);
    case RecurrenceDuration.CONTINUOUS:
      // For continuous, we'll generate occurrences for the next 2 years
      return addYears(startDate, 2);
    default:
      return addYears(startDate, 1);
  }
}
